### ISSUE TITLE
VPN List

### ISSUE THREAD

**Issue by IMmmKI** [Scrumplex/Sprummlbot#1]
Hey man :)

I was wondering where you get your VPN list from? Since I have test with some of my VPNs and I am able to bypass the kick. 

Also what port do you connect out from the bot to your services? 

Thanks :)

**Comment by liz3** [comment]
The VPN service is a extern laying service.
Trough this is a open-source project, the VPN checker its self is not.

Regards
Liz3

**Comment by svenmasuhr** [comment]
Closed due to no response.
