### ISSUE TITLE
Does not generate some config files

### ISSUE THREAD

**Issue by am4nr** [Scrumplex/Sprummlbot#3]
The but does not generate all config files, if i want to start the bot it'll crash because they're missing

**Comment by Scrumplex** [comment]
Already fixing that bug! wait for the next update (eta 1h)

**Comment by am4nr** [comment]
now i get this error:
[code]Error occurred during initialization of VM
Could not reserve enough space for object heap
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.[/code]

**Comment by Scrumplex** [comment]
How are you starting the bot?

**Comment by am4nr** [comment]
That happens when I use "java -jar Sprummlbot.jar -setupConfigs"

**Comment by Scrumplex** [comment]
so the error says, that you don't have enough ram space
look if your server / pc has 512mb ram free

**Comment by am4nr** [comment]
it got like 8gb ram free^^

**Comment by Scrumplex** [comment]
That's not normal :/ That error comes from java.

**Comment by am4nr** [comment]
any idea how to work around it?

**Comment by Scrumplex** [comment]
Depends. Do you have java 7 or 8, 32Bit or 64Bit Linux or Windows

**Comment by am4nr** [comment]
Ubuntu15.04-64
and did everything like it's shown in the wiki installation thread for linux

**Comment by Scrumplex** [comment]
k. try java -version and say if it prints an error

**Comment by am4nr** [comment]
same error
Error occurred during initialization of VM
Could not reserve enough space for object heap
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by Scrumplex** [comment]
Okay then try to reinstall java: apt-get remove openjdk-8-jre && apt-get autoremove && apt-get install openjdk-8-jre

**Comment by am4nr** [comment]
works now, thanks :)

**Comment by Scrumplex** [comment]
No problem :)

**Comment by am4nr** [comment]
btw whats the default wi password?

**Comment by am4nr** [comment]
btw what's the default wi password?

**Comment by Scrumplex** [comment]
You need to add your unique Id to the clienrs.ini under Webinterface Login and then write the bot !login
Then you get your login credentials

**Comment by am4nr** [comment]
aight! thanks buddy

**Comment by Scrumplex** [comment]
No prob

**Comment by am4nr** [comment]
Why is the bot disconnecting almost instantly O.o

**Comment by Scrumplex** [comment]
Oh umm. Okay... You did something wrong. Try to rejoin?

**Comment by am4nr** [comment]
now it stays connected but the webinterface still doesn't show anything

**Comment by Scrumplex** [comment]
I know that problem with the WI. How many users do you have on your server at the moment?

**Comment by am4nr** [comment]
2 users are online atm

**Comment by Scrumplex** [comment]
Lol. I had that problem on servers with many users. :/ I will try to fix this. Sorry for that

**Comment by Scrumplex** [comment]
My skype: scrumplex (I am also german :))
